#!/usr/bin/env bash
#using puppets to connect

file {'/etc/ssh/ssh_config':
 ensure => present,
}

file_line { 'Turn off passwd auth':
 path	=> 'etc/ssh/ssh_config',
 line	=> 'PaaswordAuthentication no',
 match	=> '^#PasswordAuthentication',
}

file_line { 'Decalre Identity file':
 path	=> 'etc/ssh/ssh_config',
 line	=> 'IdentityFile ~/.ssh/school',
 match	=> '^#IdentityFile',
}
